version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
        # volumes:
        # - db-data:/var/lib/postgresql/data

        #volumes:
  #  db-data:
