FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1
ADD schema.sql /docker-entrypoint-initdb.d
    #MYSQL_DATABASE=Transaction \
    #one
    #Mysql=1
    #MYSQL_USER=expense \
    #MYSQL_PASSWORD=ExpenseApp@1
